### PR TITLE
Adds --force-cache-fetch to forcibly fetch relocatable assets without prompt

### PR DESCRIPTION
**Pull request by prometheansacrifice**
@ulrikstrid What should we name this option? I'm seem to be bad at naming things 😄

### CODE REVIEW

**Comment by prometheansacrifice** [comment]
Maybe it should be just `--fetch-cache=yes|no` ?

**Comment by ulrikstrid** [comment]
You could go with the `opam` way and just add a `-y` flag that auto-accepts everything. Or `--fetch-cache-no-prompt`

**Comment by prometheansacrifice** [comment]
Great suggestion!

**Comment by prometheansacrifice** [comment]
Settled with `--fetch-cached` as an optional boolean (ie three values, Some(true), Some(false) and None). `-y` is very useful for the CI and will introduce it in a separate PR - it involves some careful consideration of all possible codepaths it could lead too (We have two choices right now that the user would expect -y to affect and in future, this could increase)

**Pull request merged**
