### PR TITLE
Fixes for kebab function issue

### LINKED ISSUE #101: kebab function adds hyphen before characters which are not lowercase
Here are the sample string and the response.

```JS
kebab("Hello World-2020!")
'hello- -world--2-0-2-0-!'
```

### PR DESCRIPTION
**Pull request by prashant-shahi**
Fixes #101

- converting common word separators space and underscore to hyphen
- checking if a character is an alphabet and if it is uppercase before prepending with hyphen
- converting a consecutive instance of hyphens to single

With this PR, the following would be the response of the sample string:

```JS
kebab("Hello World-2020!")
'hello-world-2020!'
```

Signed-off-by: Prashant Shahi <coolboi567@gmail.com>

### CODE REVIEW

**Comment by prometheansacrifice** [comment]
@prashant-shahi This PR has modified *.bs.js files without any accompanying changes in the sources files. Also, the patch in Utils.re seems to be exactly the same as the one in other PR

**Comment by prashant-shahi** [comment]
I had the changes for the test framework first.

After this fix, I updated the branches with test files, and pushed it as well. So, the idea was the you would merge this PR first. And, then the other one.

**Comment by prometheansacrifice** [comment]
Cool. I closed this then, give that the other PR has been merged. Thanks!

**Comment by jordwalke** [comment]
Thanks for the fix!

**Pull request closed without merging**
