### PR TITLE
Support for npm like require() syntax to re-export namespaces

### PR DESCRIPTION
**Pull request by prometheansacrifice**
## About 
This PR adds support for npm like `require()` syntax so that users can alias imports on the fly

```json
"buildDirs": {
  "myapp": {
    "bin": "App.re",
    "imports": [
      "Mylib = require('../lib')"
    ],
  },
  "lib": { }
}
```

## Why?
`pesy` wants to eliminate the library/package confusion for beginners and unify them as one entity. As a first step we automatically assigned upper camel cased folder name of the subpackage as the namespace. But that started leading to collisions. Prefixing with package name was a good fix, but wasn't closing the gap between library and package. A package's imported namespace still had to be calculated.

With npm like require syntax, users dont have to guess or calculate what the imported namespace will be. They decide what namespace the imported package must be assigned - just like how we do in node/npm.

### CODE REVIEW

**Comment by prometheansacrifice** [comment]
# Table of Contents

1.  [Pending](#org2b40500)
    1.  [Handle relative imports from 'require' field](#orgec8e19f)
    2.  [Unused lwt/unix import](#orga373864)
    3.  [Deviation from Dune](#org7a44582)
    4.  ['No cmi file' for external libs](#org7f51179)


<a id="org2b40500"></a>

# Pending


<a id="orgec8e19f"></a>

## TODO Handle relative imports from 'require' field

Disable relative and npm imports from 'require' field. 'require' field solely exists to support Dune syntax.


<a id="orga373864"></a>

## TODO Unused lwt/unix import

lwt example - unused lwt/unix import. How to deal with it? Is is necessary for the code to compile?


<a id="org7a44582"></a>

## TODO Deviation from Dune

Subpackage namespaces are now determined by pesy and users have the ability to alias them. But, will it be evident
that Bar.re inside the subpackage has to be accessed with {namespace}.Bar? Even if it is aliased as Bar. Example: <https://github.com/prometheansacrifice/pesy-npm-repro-namespace>


<a id="org7f51179"></a>

## TODO 'No cmi file' for external libs

When Unix = require('unix'), dune complains of no cmi file.

**Comment by jordwalke** [comment]
This idea has a lot of potential. I think it would be very clear to people who are used to standard npm style require statements. It's just like npm, but instead of having to do it in every file, you do it once for each project or sub-library in a project.

If two *different* packages do:
```
    "Library = require('test-project/library')",
```
Is there then the same conflict we saw before with conflicting names `Library`? Or are they secretly aliased behind the scenes?

**Comment by prometheansacrifice** [comment]
> Is there then the same conflict we saw before with conflicting names Library? Or are they secretly aliased behind the scenes?

Different subpackages are namespaced including the package name. So, this isn't an issue I hope.

**Comment by prometheansacrifice** [comment]
Just tested scoped packages. For example, there is an npm package @prometheansacrifice/foo (https://www.npmjs.com/package/@prometheansacrifice/foo). It can be consumed as

```json
  "library": {
      "imports": [
        "Console = require('console/lib')",
        "Pastel = require('pastel/lib')",
        "FooLibrary = require('@prometheansacrifice/foo/library')"
      ]
  }
  ...
  "dependencies": {
    "@prometheansacrifice/foo": "*",
    "@opam/dune": "*",
    ...
  }
```

🙌

**Pull request merged**
